### ISSUE TITLE
AttributeError due to latest release of Bokeh 3.0.0

### ISSUE THREAD

**Issue by checlams** [salvadorgarciamunoz/pyphi#13]
Hi Salvador,

I recently installed pyphi and attempted to run example files. However, I encountered the following attribute error messages: `AttributeError: unexpected attribute 'plot_width' to figure` and `AttributeError: unexpected attribute 'plot_width' to figure`. 

I realized that the cause might be due to the [recent release of Bokeh 3.0.0](https://github.com/bokeh/bokeh/wiki/Migration-Guides#300), which removed several attributes/properties. For example, `plot_width` and `plot_height` have been removed. Instead, the standard `width` and `height` should be used for all layout-able models. Also, `render_mode` was removed from all annotations, with the default being canvas rendering which is what you currently specify in `pyphi_plots.py` file. After making these changes, the issues were fixed.

I just wanted to bring this to your attention. Perhaps you could incorporate some of these changes in the future. Thank you!

**Comment by salvadorgarciamunoz** [comment]
Thanks and sorry for the delay, I will check this and address it.

**Comment by salvadorgarciamunoz** [comment]
Hi again, I just checked and the last version of Bokeh distributed with the downloadable installer from anaconda is 2.4.3, since most of my students use the anaconda installer I will try to keep the tool contemporary with the version of Bokeh that comes with conda. 

Thanks again for making me aware of this issue.

**Comment by salvadorgarciamunoz** [comment]
The latest version now addresses this problem, I will mark the issue as resolved
